apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: NotIn, values: [my-app, node-app]}
    #   - {key: app, operator: In, values: [my-app, node-app]}
  template:
    metadata:
      labels:
        app: my-app
        tier: backend
    spec:
     containers:
      - name: node-app
        image: falamarcaodocker/kub-first-app
        # Check container health
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            #  httpHeaders:
          periodSeconds: 10 # how often that should be performed
          initialDelaySeconds: 5 # wait to start checking health